In [22]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

In [23]:
df = pd.read_csv('./covid19_by_country.csv')
df.head()

,Country,Tests,Test Pop,Density,Urban Pop,Quarantine,Schools,Restrictions,Hospital Bed,sex0,sex14,sex25,sex54,sex64,sex65plus,Sex Ratio,lung,Female Lung,Male Lung,Median Age,GDP 2018,Crime Index,Population 2020,Smoking 2016,Females 2018,Total Infected,Total Deaths,Total Recovered
0,Albania,NaN,NaN,105.0,63.0,NaN,NaN,NaN,2.9,1.08,1.11,1.09,0.93,0.95,0.87,0.98,11.67,7.02,17.04,32.9,1.510250e+10,40.02,2877.797,28.7,49.063095,212,10,33
1,Algeria,NaN,NaN,18.0,73.0,NaN,NaN,NaN,1.9,1.05,1.05,1.05,1.03,1.01,0.89,1.03,8.77,5.03,12.81,28.1,1.737580e+11,54.41,43851.044,15.6,49.484268,511,31,31
2,Argentina,NaN,NaN,17.0,93.0,3/20/2020,NaN,NaN,5.0,1.05,1.06,1.05,1.00,0.94,0.71,0.98,29.27,20.16,42.59,31.7,5.198715e+11,62.96,45195.774,21.8,51.237348,745,19,72
3,Armenia,694.0,4269.802594,104.0,63.0,NaN,NaN,NaN,4.2,1.13,1.14,1.06,0.93,0.84,0.67,0.94,23.86,16.17,35.99,35.1,1.243309e+10,20.78,2963.243,24.1,52.956577,424,3,30
4,Australia,31635.0,806.065560,3.0,86.0,NaN,NaN,3/23/2020,3.8,1.06,1.06,1.09,0.99,0.93,0.86,0.99,18.79,15.90,22.16,38.7,1.433904e+12,42.70,25499.884,14.7,50.199623,3984,16,244

In [24]:
df.drop(['Total Infected', 'Total Deaths', 'Total Recovered'], axis=1, inplace=True)

In [25]:
# data cleaning and summing total events by country
def preprocess_summation(df, description):
    df = df.drop(['Province/State', 'Lat', 'Long'], axis=1).groupby(['Country/Region']).sum().reset_index()
    col_name = 'Total' + ' ' + description
    df[col_name] = df.apply(lambda r: r[-1], axis=1)
    df = df[['Country/Region', col_name]]
    df.columns = ['Country', col_name]
    df.replace({'Korea, South': 'South Korea', 'Czechia': 'Czech Republic', 'Taiwan*': 'Taiwan', 'US': 'United States'}, inplace=True)
    return df

In [26]:
df_confirmed = pd.read_csv('./csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv')
total_infections = preprocess_summation(df_confirmed, 'Infected')
df = df.merge(total_infections, how='inner', on='Country')

In [27]:
df_deaths = pd.read_csv('./csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv')
total_deaths = preprocess_summation(df_deaths, 'Deaths')
df = df.merge(total_deaths, how='inner', on='Country')

In [28]:
df_recovered = pd.read_csv('./csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv')
total_recover = preprocess_summation(df_recovered, 'Recovered')
df = df.merge(total_recover, how='inner', on='Country')
df.head()

,Country,Tests,Test Pop,Density,Urban Pop,Quarantine,Schools,Restrictions,Hospital Bed,sex0,sex14,sex25,sex54,sex64,sex65plus,Sex Ratio,lung,Female Lung,Male Lung,Median Age,GDP 2018,Crime Index,Population 2020,Smoking 2016,Females 2018,Total Infected,Total Deaths,Total Recovered
0,Albania,NaN,NaN,105.0,63.0,NaN,NaN,NaN,2.9,1.08,1.11,1.09,0.93,0.95,0.87,0.98,11.67,7.02,17.04,32.9,1.510250e+10,40.02,2877.797,28.7,49.063095,259,15,67
1,Algeria,NaN,NaN,18.0,73.0,NaN,NaN,NaN,1.9,1.05,1.05,1.05,1.03,1.01,0.89,1.03,8.77,5.03,12.81,28.1,1.737580e+11,54.41,43851.044,15.6,49.484268,847,58,61
2,Argentina,NaN,NaN,17.0,93.0,3/20/2020,NaN,NaN,5.0,1.05,1.06,1.05,1.00,0.94,0.71,0.98,29.27,20.16,42.59,31.7,5.198715e+11,62.96,45195.774,21.8,51.237348,1054,28,248
3,Armenia,694.0,4269.802594,104.0,63.0,NaN,NaN,NaN,4.2,1.13,1.14,1.06,0.93,0.84,0.67,0.94,23.86,16.17,35.99,35.1,1.243309e+10,20.78,2963.243,24.1,52.956577,571,4,31
4,Australia,31635.0,806.065560,3.0,86.0,NaN,NaN,3/23/2020,3.8,1.06,1.06,1.09,0.99,0.93,0.86,0.99,18.79,15.90,22.16,38.7,1.433904e+12,42.70,25499.884,14.7,50.199623,4862,20,422

In [29]:
df.to_csv('covid19_by_country.csv', index=False)